### ISSUE TITLE
About the candidate relaxations of relax and safe list when testing RISC-V

### ISSUE THREAD

**Issue by DehengYang** [litmus-tests/litmus-tests-riscv#9]
Dear Authors,

Sorry for interrupting you here. I am very interested in running litmus tests for the RISC-V concurrency architecture, and when I am studying this repo, I noticed that there are many X.conf files in each test folder. I am confused about two aspects, which I would like to report for your guidance:

1. how can we determine the candidate relaxations of relax and safe list. For example, the `litmus-tests-riscv/tests/non-mixed-size/CO/X.conf` file includes:
```
-safe Fence.rw.rws**,Pos**,Rfe,Fre,Wse
# empty relax list
```

And the  `litmus-tests-riscv/tests/non-mixed-size/ATOMICS/CO/X.conf` file includes:
```
-safe Fence.rw.rws**,Pos**,Rfe,Fre,Wse
-relax Fence.rw.rws**XX,Fence.rw.rws**XP,Fence.rw.rws**PX,Pos**XX,Pos**XP,Pos**PX,RfeXX,RfeXP,RfePX,FreXX,FreXP,FrePX,WseXX,WseXP,WsePX
```

**I cannot figure out what and how should we put into the relax and safe list. It would be sincerely appreciated if any help could be provided. Thank you!** 

2. I noticed that many X.conf files include a parameter "-variant", and its value is often `ConstsInInit` (sometimes `AsAMO`). **How should we use this parameter and specify its value? As I fail to find any explanation in the official diy7 tutorial, I would like to ask for your help about this.** 

Sorry again for my potentially very simple questions. And thank you in advance for your time and help!

Yours sincerely,
Deheng

**Comment by fshaked** [comment]
Hi @DehengYang,

The `X.conf` files are part of the internal mechanism for generating the litmus tests (using herdtools and diy7). The tests have already been generated and you can see them in the same folder with the `X.conf` file. To determine if a specific litmus test is allowed or forbidden by the architecture you should check the logs in the `model-results` folder.

Best,
Shaked

**Comment by DehengYang** [comment]
Dear @fshaked ，

Thank you very much for the prompt guidance. That really helps.

I noticed that there are in total 41 `X.conf` files in this project. Are these files automatically generated or manually written according to the internal mechanism for generating the litmus tests? Is there any documentation about the generation of X.conf files that could serve as a reference for me to explore? Thank you!

And for the `litmus-tests-riscv/tests/non-mixed-size/CO/X.conf` file that includes:

```
-safe Fence.rw.rws**,Pos**,Rfe,Fre,Wse
# empty relax list
```
Is it allowed/appropriate if the relax list (e.g., `PodWR`) is added to this X.conf file?

Thank you again for the great help.

Yours  sincerely,
Deheng

**Comment by fshaked** [comment]
The `X.conf`, and the `build.sh` files are hand written. If a folder has a `build.sh` file, this file generated the tests in the folder (the `X.conf` file is used by the script, with additional processing), otherwise the tests were generated by calling `diy7 -conf X.conf` directly. Some of the `build.sh` files use [rmem](https://github.com/rems-project/rmem/), which could be a bit tricky to build at the moment. 

The syntax of `X.conf` files should be documented in [herdtools7](https://github.com/herd/herdtools7), but it's basically the normal options of diy7, one in each line, lines starting with # are ignored.

The CO (coherence) tests involve a single memory location, so `Pod*` edges (which are between two different memory locations) are not relevant in this case. Moreover, I think relax edges are meant to be used when you want to check a specific relaxation, and in CO we do something a bit different. If you are trying to add `PodWR` anyway, and you don't see new tests generated, you might need to increase `-ins 2`, or add more edge kinds, to allow cycles with two memory locations to close (@maranget is the expert).

**Comment by DehengYang** [comment]
Dear @fshaked ,

Get it. Thank you so much for the detailed guidance. These comments, especially the description of the relax and safe list, are super helpful to me. 

Many thanks and wish you a great week!

Yours sincerely,
Deheng
